[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["server/app.js", "server/data/absences.json"]
